name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.15.0'  # Adjust this as needed

    - name: Install dependencies
      run: npm install
      working-directory: ./svelte-hello-world  # Change to your Svelte app directory

    - name: Build
      run: npm run build
      working-directory: ./svelte-hello-world  # Change to your Svelte app directory

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./svelte-hello-world/public  # Change to the build output directory
